### ISSUE TITLE
Replace dependent plug-ins

### ISSUE THREAD

**Issue by usercao** [laststance/react-typescript-todomvc-2022#596]
#### Can we replace `@reach/router` with ` react-router v6` for the following reasons?
1. `@reach/router` is an experimental product developed by the same group of developers
2. ` react-router` is the most popular plug-in used by users
3. ` react-router v6` contains all the functions of `@reach/router` or even better

**Comment by ryota-murakami** [comment]
close https://github.com/laststance/react-typescript-todomvc-2022/commit/741534db9ef339f03b0095e392b59a13f7fa0f39
